version: 2
sources:
  - name: RAW
    description: This is as source for STAGE
    database: MYDB
    tables:
      - name: CUSTOMER
      - name: ORDERS
      - name: LINEITEM
      - name: NATION
      - name: V_CUSTOMER
      - name: V_ORDERS
      - name: V_LINEITEM
      - name: V_NATION
  - name: STAGE
    description: This is a source for Publish
    database: MYDB
    tables:
      - name: CUSTOMER
      - name: ORDERS
      - name: LINEITEM
      - name: NATION